### PR TITLE
Add cross-platform support

### PR DESCRIPTION
**Pull request by valpackett**
Tested on FreeBSD and OpenBSD. Should work on Darwin and NetBSD too, in theory.

### CODE REVIEW

**Comment by krytarowski** [comment]
NetBSD part at least for __errno is correct.

**Comment by tailhook** [comment]
Looks good, except barely discarding flags looks incorrect. I think we should remove `local_exchange` methods on platforms which do not support `renameat2`. Thoughts?

**Comment by valpackett** [comment]
Yeah, makes sense. Removed `local_exchange` on non-Linux platforms.

**Comment by tailhook** [comment]
Great. Thanks!

I also want to add hardlink support and will release an update shortly after that.

**Comment by tailhook** [comment]
Released as `v0.1.12`, hopefully, I've not broken any cross-platform things.

**Comment by valpackett** [comment]
Yeah, tests still pass on FreeBSD.

**Pull request merged**
